### ISSUE TITLE
Error whe installing bobtemplates.plone

### ISSUE THREAD

**Issue by danielhz** [plone/bobtemplates.plone#107]
I got the following error when installing `mrbob` in a `virtualenv`:

    $ virtualenv --no-site-packages --python=python2.7 .
    Running virtualenv with interpreter /usr/bin/python2.7
    New python executable in ./bin/python2.7
    Also creating executable in ./bin/python
    Installing setuptools, pip...done.
    $ bin/pip install bobtemplates.plone
    Downloading/unpacking bobtemplates.plone
    Downloading bobtemplates.plone-0.11.tar.gz
    Running setup.py (path:/tmp/pip-build-U1Pphi/bobtemplates.plone/setup.py) egg_info for package bobtemplates.plone
        warning: no previously-included files matching '*pyc' found anywhere in distribution
    Requirement already satisfied (use --upgrade to upgrade): setuptools in ./lib/python2.7/site-packages (from bobtemplates.plone)
    Downloading/unpacking mr.bob (from bobtemplates.plone)
       Downloading mr.bob-0.1.2.tar.gz
    Cleaning up...
    Exception:
    Traceback (most recent call last):
      File "/home/daniel/workspace/testing/mrbob/local/lib/python2.7/site-packages/pip/basecommand.py", line 122, in main
        status = self.run(options, args)
      File "/home/daniel/workspace/testing/mrbob/local/lib/python2.7/site-packages/pip/commands/install.py", line 290, in run
        requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
      File "/home/daniel/workspace/testing/mrbob/local/lib/python2.7/site-packages/pip/req.py", line 1198, in prepare_files
        do_download,
      File "/home/daniel/workspace/testing/mrbob/local/lib/python2.7/site-packages/pip/req.py", line 1376, in unpack_url
        self.session,
      File "/home/daniel/workspace/testing/mrbob/local/lib/python2.7/site-packages/pip/download.py", line 582, in unpack_http_url
        unpack_file(temp_location, location, content_type, link)
      File "/home/daniel/workspace/testing/mrbob/local/lib/python2.7/site-packages/pip/util.py", line 644, in unpack_file
        untar_file(filename, location)
      File "/home/daniel/workspace/testing/mrbob/local/lib/python2.7/site-packages/pip/util.py", line 575, in untar_file
        path = os.path.join(location, fn)
      File "/home/daniel/workspace/testing/mrbob/lib/python2.7/posixpath.py", line 80, in join
        path += '/' + b
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc4 in position 31: ordinal not in range(128)

    Storing debug log for failure in /home/daniel/.pip/pip.log

However, the following works:

    $ virtualenv --no-site-packages --python=python2.7 .
    $ bin/pip install mr.bob
    $ bib/pip install bobtemplates.plone

Thus, why it works when I install mr.bob first?

**Comment by mauritsvanrees** [comment]
I see the same error.  I added a pdb in pip/util.py line 575 where it does `path = os.path.join(location, fn)`.  It tries to combine these two:

```
(Pdb) location
u'/Users/mauritsvanrees/tmp/venv/build/mr.bob'
(Pdb) fn
'mrbob/tests/templates/encoding\xc4\x8d'
```

mr.bob indeed has a file `templates/encodingč/mapča/ća.bob`.

Ah, but when I first upgrade pip, it works: `bin/pip install -U pip`.  I had version 1.5.6 at first, and now version 7.1.2. 

Uninstall fails though:

```
Exception:
Traceback (most recent call last):
  File "/Users/mauritsvanrees/tmp/venv3/lib/python2.7/site-packages/pip/basecommand.py", line 211, in main
    status = self.run(options, args)
  File "/Users/mauritsvanrees/tmp/venv3/lib/python2.7/site-packages/pip/commands/uninstall.py", line 76, in run
    requirement_set.uninstall(auto_confirm=options.yes)
  File "/Users/mauritsvanrees/tmp/venv3/lib/python2.7/site-packages/pip/req/req_set.py", line 305, in uninstall
    req.uninstall(auto_confirm=auto_confirm)
  File "/Users/mauritsvanrees/tmp/venv3/lib/python2.7/site-packages/pip/req/req_install.py", line 716, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/Users/mauritsvanrees/tmp/venv3/lib/python2.7/site-packages/pip/req/req_uninstall.py", line 125, in remove
    renames(path, new_path)
  File "/Users/mauritsvanrees/tmp/venv3/lib/python2.7/site-packages/pip/utils/__init__.py", line 315, in renames
    shutil.move(old, new)
  File "/Users/mauritsvanrees/buildout/python2.7/parts/opt/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/Users/mauritsvanrees/buildout/python2.7/parts/opt/lib/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/Users/mauritsvanrees/buildout/python2.7/parts/opt/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: '/Users/mauritsvanrees/tmp/venv3/lib/python2.7/site-packages/mrbob/tests/templates/encoding\xc4\x8d/map\xc4\x8da/\xc4\x87a.bob'
```

Anyway, this all is an issue with pip.
