### ISSUE TITLE
AttributeError: 'bool' object has no attribute 'lower' in content_type template

### ISSUE THREAD

**Issue by MrTango** [plone/bobtemplates.plone#313]
```
--> Content type name (Allowed: _ a-z A-Z and whitespace) [Todo Task]: CropContainer

--> Content type description: Container for Crop objects

--> Use XML Model [y]: 

--> Dexterity base class (Container/Item) [Container]: 

--> Should the content type globally addable? [y]: y

--> Should we filter content types to be added to this container? [n]: y

--> Create a content type class [y]: 


Traceback (most recent call last):
  File "/home/maik/.local/bin/mrbob", line 11, in <module>
    sys.exit(main())
  File "/home/maik/.local/lib/python2.7/site-packages/mrbob/cli.py", line 175, in main
    c.render()
  File "/home/maik/.local/lib/python2.7/site-packages/mrbob/configurator.py", line 192, in render
    self.ignored_directories)
  File "/home/maik/.local/lib/python2.7/site-packages/mrbob/rendering.py", line 82, in render_structure
    renderer,
  File "/home/maik/.local/lib/python2.7/site-packages/mrbob/rendering.py", line 102, in render_template
    output = renderer(source_output, variables)
  File "/home/maik/.local/lib/python2.7/site-packages/mrbob/rendering.py", line 22, in <lambda>
    jinja2_renderer = lambda s, v: jinja2_env.from_string(s).render(parse_variables(v))
  File "/home/maik/.local/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/maik/.local/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<template>", line 7, in top-level template code
  File "/home/maik/.local/lib/python2.7/site-packages/bobtemplates/plone/base.py", line 29, in to_boolean
    return hooks.to_boolean(None, None, value)
  File "/home/maik/.local/lib/python2.7/site-packages/mrbob/hooks.py", line 22, in to_boolean
    value = answer.lower()
AttributeError: 'bool' object has no attribute 'lower'
```

**Comment by MrTango** [comment]
The to_boolean method couldn't handle already boolean values, only strings.
The test didn't cover this, because we are there only fill in strings.
