### ISSUE TITLE
Missing comma after `PLONE_FIXTURE` import in bobtemplates/plone/addon/src/+package.namespace+/+package.name+/testing.py.bob

### ISSUE THREAD

**Issue by me-kell** [plone/bobtemplates.plone#527]
Missing comma after `PLONE_FIXTURE` import in `bobtemplates/plone/addon/src/+package.namespace+/+package.name+/testing.py.bob`

https://github.com/plone/bobtemplates.plone/blob/65d76d0d971068f4155f8a022cba7d12570236f0/bobtemplates/plone/addon/src/%2Bpackage.namespace%2B/%2Bpackage.name%2B/testing.py.bob#L11

```
Test-module import failures:

Module: myaddon.name.tests.test_robot

Traceback (most recent call last):
  File "/home/Plone-6.0.0b3/src/myaddon.name/src/myaddon/name/tests/test_robot.py", line 2, in <module>
    from myaddon.name.testing import MYADDON_NAME_ACCEPTANCE_TESTING  # noqa: E501
  File "/home/Plone-6.0.0b3/src/myaddon.name/src/myaddon/name/testing.py", line 8
    PloneSandboxLayer,
    ^
SyntaxError: invalid syntax
```

**Comment by pandeyprashant123-coder** [comment]
hey @me-kell  I have addressed the issue

**Comment by fredvd** [comment]
fixed
